jlib: fix unsupported operand type when setting log level
This fixes the following issue when log_levels_find() is used (for
example when setting a log level delta using JLIB_log_levels):
[...]
    scripts/jlib.py:424:log(): level += log_levels_find( caller)
    scripts/jlib.py:334:log_levels_find(): tb = traceback.extract_stack( None, 1+caller)
TypeError: unsupported operand type(s) for +: 'int' and 'FrameInfo'

Note that this fix get JLIB_log_levels working, but it might be
incorrect.

Signed-off-by: Raphaël Mélotte <raphael.melotte@mind.be>